name: lodestar-git-api

servicePort: 8080

imageName: "quay.io/rht-labs/omp-git-api"
imageTag: "latest" # This is intended to be overridden by the parent Helm chart.

gitlabRef: "master"

config:
  hookFile:
    path: /runtime
    name: webhooks.yaml
  configFile:
    path: /runtime
    name: lodestar-runtime-config.yaml
